### ISSUE TITLE
Assets not loading when running server

### ISSUE THREAD

**Issue by SlowburnAZ** [germsvel/watwitter#6]
![image](https://user-images.githubusercontent.com/5659169/171301707-54bf7bd6-931b-40dc-a7f6-84613441000a.png)

I'm sure I'm doing something silly here, but when the server is up and running (with either `mix phx.server` or `iex -S mix phx.server`), the page doesn't load any assets, as it seems the css and js files can't be reached.

I'm running this inside of a default WSL2 Ubuntu installation, if that makes any difference.

**Comment by SlowburnAZ** [comment]
Actually, I just noticed that I'm also seeing "Javascript heap out of memory" errors in the console.  I'll look further into this and report back any solutions, or just close this if necessary...  I have a feeling this may be due to the Ubuntu installation I have in WSL2.

**Comment by SlowburnAZ** [comment]
So, yes...  seems this was a multi-faceted issue.

I updated the Ubuntu distro inside WSL2 to 22.04 LTS., along with adding "export NODE_OPTIONS=--max-old-space-size=4096" to my .bashrc file.  Also using the latest LTS NodeJS version, currently v16.15.0.

With the default Ubuntu distro, adding the NODE_OPTIONS export was not working.

**Comment by germsvel** [comment]
Thanks for looking into this!
