### ISSUE TITLE
Issue with Testing Broadcasting Part 1

### ISSUE THREAD

**Issue by SlowburnAZ** [germsvel/watwitter#7]
In the video, we're using the "16-testing-brodcasting-likes-part-1" branch...  however, when it comes to adding the broadcast of the `:post_updated` event, there's no corresponding `handle_info()` clause for the `:post_updated`, so the testing fails, despite the video showing that the test succeeds.

Seems that maybe this branch is missing the following function in timeline_live.ex...?:

def handle_info({:post_updated, post}, socket) do
  send_update(PostComponent, id: post.id)

  {:noreply, socket}
end

**Comment by germsvel** [comment]
@SlowburnAZ thanks for opening this issue, and sorry for the confusion. I think I know what's happening. 

**At the end of Part 1 there _should_ be one test failing.** 

In _Testing Broadcasting Likes_ (part 1), we're only testing one side of the broadcasting equation (the sending side). So, we're focused on a single test: _"liking a post broadcasts message to other timelines"_. 

That's the test that I show passing in the video. 

But if you run the entire _post_component_test.exs_ file, you'll definitely see an error with `handle_info/2` callback being undefined.

```elixir
** (FunctionClauseError) no function clause matching in WatwitterWeb.TimelineLive.handle_info/2
```

**That's what we handle in the Part 2, when we test the receiving side**. Let me know if that's what you're seeing or if it's something else.

**Comment by SlowburnAZ** [comment]
Ah, yup, I'm a dummy!  I thought maybe something had been missed, or I missed something...  sounds like I did ;-).  Thanks, German!

**Comment by germsvel** [comment]
Not at all! Thanks for opening the issue. I realize _now_ that it's confusing because it's not immediately apparent that I'm only running the one test.
